"""Add more fields in parking spot

Revision ID: 9a6b773e913e
Revises: f186c5d316e8
Create Date: 2025-08-01 00:41:39.391437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6b773e913e'
down_revision: Union[str, None] = 'f186c5d316e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_spots', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('parking_spots', sa.Column('parking_type', sa.String(length=50), nullable=True))
    op.add_column('parking_spots', sa.Column('max_vehicle_size', sa.String(length=20), nullable=True))
    op.add_column('parking_spots', sa.Column('amenities', sa.Text(), nullable=True))
    op.add_column('parking_spots', sa.Column('images', sa.Text(), nullable=True))
    op.add_column('parking_spots', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('parking_spots', sa.Column('availability_hours', sa.String(length=100), nullable=True))
    op.add_column('parking_spots', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('parking_spots', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('parking_spots', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_spots', 'is_active')
    op.drop_column('parking_spots', 'updated_by')
    op.drop_column('parking_spots', 'created_by')
    op.drop_column('parking_spots', 'availability_hours')
    op.drop_column('parking_spots', 'contact_phone')
    op.drop_column('parking_spots', 'images')
    op.drop_column('parking_spots', 'amenities')
    op.drop_column('parking_spots', 'max_vehicle_size')
    op.drop_column('parking_spots', 'parking_type')
    op.drop_column('parking_spots', 'description')
    # ### end Alembic commands ###
